name: "Issue Tag"
description: "Adds tags to a YouTrack Issue"
branding:
  icon: tag
  color: blue
inputs:
  issue:
    required: true
    description: "YouTrack Issue ID (e.g. SDK-123)"
  tags:
    required: true
    description: "Comma-separated list of tags to add to the issue"
  token:
    required: true
    description: "YouTrack API token"
  url:
    required: true
    description: "YouTrack base url"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        python "${{ github.action_path }}/../../youtrack.py" \
          --base-url="${{ inputs.url }}" \
          --token="${{ inputs.token }}" \
          issue-tag \
          --issue="${{ inputs.issue }}" \
          --tags="${{ inputs.tags }}"
