name: "Issue Exists"
description: "Checks if a YouTrack Issue exists"
branding:
  icon: check-square
  color: blue
inputs:
  issue:
    required: true
    description: "YouTrack Issue ID (e.g. PROD-80)"
  token:
    required: true
    description: "YouTrack API token"
  url:
    required: true
    description: "YouTrack base url"
outputs:
  exists:
    description: "1 if the Issue exists else 0"
    value: ${{ steps.check.outputs.exists }}
runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        issue=`python "${{ github.action_path }}/../../youtrack.py" \
          --base-url="${{ inputs.url }}" \
          --token="${{ inputs.token }}" \
          get-issue \
          --issue="${{ inputs.issue }}"`

        if [[ $issue ]]; then
          echo "exists=1" >> $GITHUB_OUTPUT
        else
          echo "exists=0" >> $GITHUB_OUTPUT
        fi
