name: Version Exists
description: Checks if a YouTrack Version exists
branding:
  icon: check-square
  color: blue
inputs:
  project:
    required: true
    description: YouTrack Project Key (e.g. FW)
  version:
    required: true
    description: YouTrack Version Name (e.g. 3.01.03)
  token:
    required: true
    description: YouTrack API token
  url:
    required: true
    description: YouTrack base url
outputs:
  exists:
    description: 1 if the Version exists else 0
    value: ${{ steps.check.outputs.exists }}
runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        version=`python "${{ github.action_path }}/../../youtrack.py" \
          --base-url="${{ inputs.url }}" \
          --token="${{ inputs.token }}" \
          get-version \
          --project="${{ inputs.project }}" \
          --version="${{ inputs.version }}"`

        if [[ $version ]]; then
          echo "exists=1" >> $GITHUB_OUTPUT
        else
          echo "exists=0" >> $GITHUB_OUTPUT
        fi
