name: "Issue Comment"
description: "Adds a Comment to a YouTrack Issue"
branding:
  icon: message-square
  color: blue
inputs:
  comment_file:
    required: true
    description: "Path to a json file with the comments (dict with issue as key and comment as value)"
  token:
    required: true
    description: "YouTrack API token"
  url:
    required: true
    description: "YouTrack base url"
runs:
  using: composite
  steps:
    - shell: powershell
      if: runner.os == 'Windows'
      run: |
        python "${{ github.action_path }}/../../youtrack.py" `
        --base-url="${{ inputs.url }}" `
        --token="${{ inputs.token }}" `
        add-comments `
        --comments-file="${{ inputs.comment_file }}"
    - shell: bash
      if: runner.os != 'Windows'
      run: |
        python "${{ github.action_path }}/../../youtrack.py" \
          --base-url="${{ inputs.url }}" \
          --token="${{ inputs.token }}" \
          add-comments \
          --comments-file="${{ inputs.comment_file }}"
