name: "Issue Watch"
description: "Adds watchers to a YouTrack Issue"
branding:
  icon: eye
  color: blue
inputs:
  issue:
    required: true
    description: "YouTrack Issue ID (e.g. SDK-123)"
  logins:
    required: true
    description: "Comma-separated list of watcher YouTrack logins"
  token:
    required: true
    description: "YouTrack API token"
  url:
    required: true
    description: "YouTrack base url"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        python "${{ github.action_path }}/../../youtrack.py" \
          --base-url="${{ inputs.url }}" \
          --token="${{ inputs.token }}" \
          issue-watch \
          --issue="${{ inputs.issue }}" \
          --logins="${{ inputs.logins }}"
