on:
  workflow_call:
    inputs:
      if:
        description: 'overwrites if condition for this action'
        default: ${{ github.ref_protected }}
        required: false
        type: boolean
jobs:
  jira-integration-push:
    name: Comment pushed commit messages
    runs-on: ubuntu-24.04
    if: inputs.if
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout ci-scripts repository
        uses: actions/checkout@v4
        with:
          repository: baltech-ag/ci-scripts
          path: ci-scripts
      - name: Set default env
        run: |
          echo "CI_COMMIT_BEFORE_SHA=${{ github.event.before }}" >> $GITHUB_ENV
          echo "CI_COMMIT_SHA=${{ github.event.after }}" >> $GITHUB_ENV
          echo "CI_COMMIT_REF_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Set env for pull request event
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "CI_COMMIT_BEFORE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "CI_COMMIT_SHA=" >> $GITHUB_ENV
          echo "CI_COMMIT_REF_NAME=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
      - name: Jira integration
        run: python ci-scripts/build_push_comment.py > jira_comment.json
        env:
          CI_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          CI_PROJECT_NAME: ${{ github.event.repository.name }}
          CI_PROJECT_DIR: ${{ github.workspace }}
      - name: Post Comment
        uses: ./ci-scripts/actions/jira-comment
        with:
          comment_file: jira_comment.json
          user: ${{ secrets.JIRA_USER }}
          password: ${{ secrets.JIRA_PASSWORD }}
          url: ${{ secrets.JIRA_URL }}
      - name: Cleanup
        if: always()
        run: rm -rf ci-scripts
