on:
  workflow_call:
jobs:
  jira-integration-pr:
    name: Comment on new pull request
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout ci-scripts repository
        uses: actions/checkout@v4
        with:
          repository: baltech-ag/ci-scripts
          path: ci-scripts
      - name: Build Comment
        run: python ci-scripts/build_pr_comment.py > jira_comment.json
        env:
          CI_PR_AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
          CI_PR_TITLE: ${{ github.event.pull_request.title }}
          CI_PR_URL: ${{ github.event.pull_request.html_url }}
          CI_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          CI_BASE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
          CI_PROJECT_NAME: ${{ github.event.repository.name }}
          CI_PROJECT_URL: ${{ github.event.repository.html_url }}
      - name: Post Comment
        uses: ./ci-scripts/actions/jira-comment
        with:
          comment_file: jira_comment.json
          user: ${{ secrets.JIRA_USER }}
          password: ${{ secrets.JIRA_PASSWORD }}
          url: ${{ secrets.JIRA_URL }}
      - name: Cleanup
        if: always()
        run: rm -rf ci-scripts
