name: Release Actions - Deploy build to Fileserver
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
      projects-folder:
        type: string
        required: true
      project-name:
        type: string
        required: true
      version:
        type: string
        required: true
jobs:
  deploy-onedrive:
    name: Deploy build to OneDrive
    runs-on: [self-hosted, windows, onedrive]
    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./artifacts
      - name: Get Artifact Infos
        id: artifact
        run: |
          $artifact = (Get-ChildItem -Path "${{ steps.download-artifact.outputs.download-path }}")[0]
          ("path=" + $artifact.FullName) | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          ("extension=" + $artifact.Extension) | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Deploy
        shell: cmd
        run: |
          setlocal EnableDelayedExpansion
          set "SOURCE=${{ steps.artifact.outputs.path }}"
          set "VERSION=${{ inputs.version }}"
          echo Source file: !SOURCE!
          set "DEST=%OneDriveCommercial%\F&E\Projekte\${{ inputs.projects-folder }}\${{ inputs.project-name }}\bin\${{ inputs.project-name }}_%VERSION:.=_%${{ steps.artifact.outputs.extension }}"
          if not exist "!DEST!\.." mkdir "!DEST!\.."
          echo Destination file: !DEST!
          copy "!SOURCE!" "!DEST!"
